// Generated by tauri3-specta. Do not edit.

import { invoke as __t3Invoke } from "@tauri-apps/api/core"
import {
  type EventCallback as __t3Callback,
  emit as __t3Emit,
  emitTo as __t3EmitTo,
  listen as __t3Listen,
  once as __t3Once,
  type EventTarget as __t3Target
} from "@tauri-apps/api/event"

export const commands = {
  extensionBundles: (): Promise<BundledExtension[]> => __t3Invoke<BundledExtension[]>("extension_bundles"),
  extensionPrepareInstall: (args: {
    expectedId: string | null
  }): Promise<
    { format: "current"; path: string; id: string } | { format: "legacy"; prepared: PreparedImport } | null
  > =>
    __t3Invoke<{ format: "current"; path: string; id: string } | { format: "legacy"; prepared: PreparedImport } | null>(
      "extension_prepare_install",
      args
    ),
  legacyStageImport: (args: { ticket: string; manifest: JsonValue; main: string }): Promise<StagedImport> =>
    __t3Invoke<StagedImport>("legacy_stage_import", args),
  legacyTakeInitialData: (args: {
    extensionId: string
  }): Promise<null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue } | null> =>
    __t3Invoke<null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue } | null>(
      "legacy_take_initial_data",
      args
    ),
  legacyAckInitialData: (args: { extensionId: string }): Promise<null> =>
    __t3Invoke<null>("legacy_ack_initial_data", args),
  legacyCleanupImport: (args: { extensionId: string }): Promise<null> =>
    __t3Invoke<null>("legacy_cleanup_import", args),
  legacyHttp: (args: { extensionId: string; request: HttpRequest }): Promise<HttpResponse> =>
    __t3Invoke<HttpResponse>("legacy_http", args),
  extensionHttp: (args: { extensionId: string; request: HttpRequest }): Promise<HttpResponse> =>
    __t3Invoke<HttpResponse>("extension_http", args),
  extensionCleanupGrants: (args: { extensionId: string }): Promise<null> =>
    __t3Invoke<null>("extension_cleanup_grants", args),
  extensionFile: (args: { extensionId: string; request: FileRequest }): Promise<FileResponse> =>
    __t3Invoke<FileResponse>("extension_file", args),
  extensionDirectories: (args: { extensionId: string }): Promise<DirectoryGrant[]> =>
    __t3Invoke<DirectoryGrant[]>("extension_directories", args),
  extensionPickDirectory: (args: {
    extensionId: string
  }): Promise<{
    scope: string
    path: string
  } | null> =>
    __t3Invoke<{
      scope: string
      path: string
    } | null>("extension_pick_directory", args),
  legacyFile: (args: { extensionId: string; request: FileRequest }): Promise<FileResponse> =>
    __t3Invoke<FileResponse>("legacy_file", args),
  legacyDirectories: (args: { extensionId: string }): Promise<DirectoryGrant[]> =>
    __t3Invoke<DirectoryGrant[]>("legacy_directories", args),
  legacyPickDirectory: (args: {
    extensionId: string
  }): Promise<{
    scope: string
    path: string
  } | null> =>
    __t3Invoke<{
      scope: string
      path: string
    } | null>("legacy_pick_directory", args),
  wallpaperList: (): Promise<ImportedImage[]> => __t3Invoke<ImportedImage[]>("wallpaper_list"),
  wallpaperImport: (args: {
    locale: string | null
  }): Promise<{
    id: string
    name: string
    width: number
    height: number
  } | null> =>
    __t3Invoke<{
      id: string
      name: string
      width: number
      height: number
    } | null>("wallpaper_import", args),
  wallpaperRemove: (args: { id: string; locale: string | null }): Promise<boolean> =>
    __t3Invoke<boolean>("wallpaper_remove", args),
  refreshTokens: (args: { apiBaseUrl: string; refreshToken: string }): Promise<RefreshedTokens> =>
    __t3Invoke<RefreshedTokens>("refresh_tokens", args),
  presentChatWindow: (): Promise<null> => __t3Invoke<null>("present_chat_window"),
  resizeChatWindow: (args: { direction: string; x: number; y: number; width: number; height: number }): Promise<null> =>
    __t3Invoke<null>("resize_chat_window", args),
  runtimeStart: (args: { connectionId: string }): Promise<null> => __t3Invoke<null>("runtime_start", args),
  runtimeSend: (args: { line: string; connectionId: string }): Promise<null> => __t3Invoke<null>("runtime_send", args),
  /**
   *  Read the same bundled executable used by the Runtime, not the ACP adapter's package version.
   */
  codexVersion: (): Promise<string> => __t3Invoke<string>("codex_version"),
  providersRead: (): Promise<Snapshot_Serialize> => __t3Invoke<Snapshot_Serialize>("providers_read"),
  providersSave: (args: {
    providerId: string
    input: {
      apiKey?: string | null
      region?: string | null
      baseUrl?: string | null
    } | null
    expectedRevision: number
  }): Promise<Snapshot_Serialize> => __t3Invoke<Snapshot_Serialize>("providers_save", args),
  providersSaveCustom: (args: {
    input: CustomInput_Deserialize
    expectedRevision: number
  }): Promise<Snapshot_Serialize> => __t3Invoke<Snapshot_Serialize>("providers_save_custom", args),
  providersRemoveCustom: (args: { providerId: string; expectedRevision: number }): Promise<Snapshot_Serialize> =>
    __t3Invoke<Snapshot_Serialize>("providers_remove_custom", args),
  providersTest: (args: { providerId: string }): Promise<TestResult> => __t3Invoke<TestResult>("providers_test", args),
  providersApply: (): Promise<Snapshot_Serialize> => __t3Invoke<Snapshot_Serialize>("providers_apply"),
  updaterGetState: (): Promise<State> => __t3Invoke<State>("updater_get_state"),
  updaterInstallAndRelaunch: (): Promise<null> => __t3Invoke<null>("updater_install_and_relaunch"),
  /**
   *  Makes `label` a child window of `main` (macOS only): it floats above the main window,
   *  follows it between Spaces and never becomes its own Stage Manager stage. Called on every
   *  open: hiding a child window (orderOut) detaches it, so reopening must re-attach.
   *  Other platforms have no such grouping; the command is a no-op there.
   */
  attachWindowToMain: (args: { label: string }): Promise<boolean> => __t3Invoke<boolean>("attach_window_to_main", args),
  readAppsInfo: (args: { names: string[]; withIcons: boolean }): Promise<AppInfo[]> =>
    __t3Invoke<AppInfo[]>("read_apps_info", args),
  openPathInApp: (args: { bundleId: string; path: string }): Promise<null> => __t3Invoke<null>("open_path_in_app", args)
} as const

/** Declared Rust errors. IPC/transport failures remain unknown. */
export type CommandErrors = {
  extensionBundles: string
  extensionPrepareInstall: string
  legacyStageImport: string
  legacyTakeInitialData: string
  legacyAckInitialData: string
  legacyCleanupImport: string
  legacyHttp: string
  extensionHttp: string
  extensionCleanupGrants: string
  extensionFile: string
  extensionDirectories: string
  extensionPickDirectory: string
  legacyFile: string
  legacyDirectories: string
  legacyPickDirectory: string
  wallpaperList: string
  wallpaperImport: string
  wallpaperRemove: string
  refreshTokens: JsonValue
  presentChatWindow: string
  resizeChatWindow: string
  runtimeStart: string
  runtimeSend: string
  codexVersion: string
  providersRead: string
  providersSave: string
  providersSaveCustom: string
  providersRemoveCustom: string
  providersTest: string
  providersApply: string
  updaterGetState: null
  updaterInstallAndRelaunch: string
  attachWindowToMain: string
  readAppsInfo: JsonValue
  openPathInApp: JsonValue
}

export const events = {
  "runtime:lines": {
    name: "runtime:lines",
    listen: (handler: __t3Callback<RuntimeLines>) => __t3Listen<RuntimeLines>("runtime:lines", handler),
    once: (handler: __t3Callback<RuntimeLines>) => __t3Once<RuntimeLines>("runtime:lines", handler),
    emit: (payload: RuntimeLines) => __t3Emit("runtime:lines", payload),
    emitTo: (target: string | __t3Target, payload: RuntimeLines) => __t3EmitTo(target, "runtime:lines", payload)
  },
  "runtime:exit": {
    name: "runtime:exit",
    listen: (handler: __t3Callback<RuntimeExit>) => __t3Listen<RuntimeExit>("runtime:exit", handler),
    once: (handler: __t3Callback<RuntimeExit>) => __t3Once<RuntimeExit>("runtime:exit", handler),
    emit: (payload: RuntimeExit) => __t3Emit("runtime:exit", payload),
    emitTo: (target: string | __t3Target, payload: RuntimeExit) => __t3EmitTo(target, "runtime:exit", payload)
  },
  "providers:changed": {
    name: "providers:changed",
    listen: (handler: __t3Callback<Snapshot_Serialize>) => __t3Listen<Snapshot_Serialize>("providers:changed", handler),
    once: (handler: __t3Callback<Snapshot_Serialize>) => __t3Once<Snapshot_Serialize>("providers:changed", handler),
    emit: (payload: Snapshot_Deserialize) => __t3Emit("providers:changed", payload),
    emitTo: (target: string | __t3Target, payload: Snapshot_Deserialize) =>
      __t3EmitTo(target, "providers:changed", payload)
  },
  "updater:state": {
    name: "updater:state",
    listen: (handler: __t3Callback<State>) => __t3Listen<State>("updater:state", handler),
    once: (handler: __t3Callback<State>) => __t3Once<State>("updater:state", handler),
    emit: (payload: State) => __t3Emit("updater:state", payload),
    emitTo: (target: string | __t3Target, payload: State) => __t3EmitTo(target, "updater:state", payload)
  },
  "menu:open-settings": {
    name: "menu:open-settings",
    listen: (handler: __t3Callback<OpenSettings>) => __t3Listen<OpenSettings>("menu:open-settings", handler),
    once: (handler: __t3Callback<OpenSettings>) => __t3Once<OpenSettings>("menu:open-settings", handler),
    emit: (payload: OpenSettings) => __t3Emit("menu:open-settings", payload),
    emitTo: (target: string | __t3Target, payload: OpenSettings) => __t3EmitTo(target, "menu:open-settings", payload)
  },
  "menu:new-chat": {
    name: "menu:new-chat",
    listen: (handler: __t3Callback<NewChat>) => __t3Listen<NewChat>("menu:new-chat", handler),
    once: (handler: __t3Callback<NewChat>) => __t3Once<NewChat>("menu:new-chat", handler),
    emit: (payload: NewChat) => __t3Emit("menu:new-chat", payload),
    emitTo: (target: string | __t3Target, payload: NewChat) => __t3EmitTo(target, "menu:new-chat", payload)
  },
  "menu:find-in-chat": {
    name: "menu:find-in-chat",
    listen: (handler: __t3Callback<FindInChat>) => __t3Listen<FindInChat>("menu:find-in-chat", handler),
    once: (handler: __t3Callback<FindInChat>) => __t3Once<FindInChat>("menu:find-in-chat", handler),
    emit: (payload: FindInChat) => __t3Emit("menu:find-in-chat", payload),
    emitTo: (target: string | __t3Target, payload: FindInChat) => __t3EmitTo(target, "menu:find-in-chat", payload)
  },
  "menu:command-palette": {
    name: "menu:command-palette",
    listen: (handler: __t3Callback<CommandPalette>) => __t3Listen<CommandPalette>("menu:command-palette", handler),
    once: (handler: __t3Callback<CommandPalette>) => __t3Once<CommandPalette>("menu:command-palette", handler),
    emit: (payload: CommandPalette) => __t3Emit("menu:command-palette", payload),
    emitTo: (target: string | __t3Target, payload: CommandPalette) =>
      __t3EmitTo(target, "menu:command-palette", payload)
  },
  "menu:open-hotkeys": {
    name: "menu:open-hotkeys",
    listen: (handler: __t3Callback<OpenHotkeys>) => __t3Listen<OpenHotkeys>("menu:open-hotkeys", handler),
    once: (handler: __t3Callback<OpenHotkeys>) => __t3Once<OpenHotkeys>("menu:open-hotkeys", handler),
    emit: (payload: OpenHotkeys) => __t3Emit("menu:open-hotkeys", payload),
    emitTo: (target: string | __t3Target, payload: OpenHotkeys) => __t3EmitTo(target, "menu:open-hotkeys", payload)
  },
  "menu:zoom-in": {
    name: "menu:zoom-in",
    listen: (handler: __t3Callback<ZoomIn>) => __t3Listen<ZoomIn>("menu:zoom-in", handler),
    once: (handler: __t3Callback<ZoomIn>) => __t3Once<ZoomIn>("menu:zoom-in", handler),
    emit: (payload: ZoomIn) => __t3Emit("menu:zoom-in", payload),
    emitTo: (target: string | __t3Target, payload: ZoomIn) => __t3EmitTo(target, "menu:zoom-in", payload)
  },
  "menu:zoom-out": {
    name: "menu:zoom-out",
    listen: (handler: __t3Callback<ZoomOut>) => __t3Listen<ZoomOut>("menu:zoom-out", handler),
    once: (handler: __t3Callback<ZoomOut>) => __t3Once<ZoomOut>("menu:zoom-out", handler),
    emit: (payload: ZoomOut) => __t3Emit("menu:zoom-out", payload),
    emitTo: (target: string | __t3Target, payload: ZoomOut) => __t3EmitTo(target, "menu:zoom-out", payload)
  },
  "menu:actual-size": {
    name: "menu:actual-size",
    listen: (handler: __t3Callback<ActualSize>) => __t3Listen<ActualSize>("menu:actual-size", handler),
    once: (handler: __t3Callback<ActualSize>) => __t3Once<ActualSize>("menu:actual-size", handler),
    emit: (payload: ActualSize) => __t3Emit("menu:actual-size", payload),
    emitTo: (target: string | __t3Target, payload: ActualSize) => __t3EmitTo(target, "menu:actual-size", payload)
  }
} as const

export type ActualSize = null

export type AppInfo = {
  name: string
  bundle_id: string
  icon: string | null
}

export type BundledExtension = {
  path: string
  id: string
  version: string
  source: string
}

export type CommandPalette = null

export type CustomInput = CustomInput_Serialize | CustomInput_Deserialize

export type CustomInput_Deserialize = {
  id?: string | null
  name: string
  apiKey?: string | null
  baseUrl: string
  models: CustomModel_Deserialize[]
}

export type CustomInput_Serialize = {
  id: string | null
  name: string
  apiKey: string | null
  baseUrl: string
  models: CustomModel_Serialize[]
}

export type CustomModel = CustomModel_Serialize | CustomModel_Deserialize

export type CustomModel_Deserialize = {
  label: string
  api_id: string
  contextWindow?: number | null
  description?: string | null
}

export type CustomModel_Serialize = {
  label: string
  api_id: string
  contextWindow?: number | null
  description?: string | null
}

export type DirectoryGrant = {
  scope: string
  path: string
}

export type DisablementReason = "invalidConfiguration"

export type FileEntry = {
  name: string
  isFile: boolean
  isDirectory: boolean
}

export type FileOperation = "read" | "write" | "mkdir" | "remove" | "list" | "stat"

export type FileRequest = {
  operation: FileOperation
  scope: string | null
  path: string
  body: number[] | null
  recursive?: boolean
}

export type FileResponse =
  | { type: "read"; body: number[] }
  | { type: "list"; entries: FileEntry[] }
  | { type: "stat"; exists: boolean; size: number; mtime: number | null; isFile: boolean; isDirectory: boolean }
  | { type: "ok" }

export type FindInChat = null

export type HttpRequest = {
  url: string
  method: string | null
  headers?: { [key in string]: string }
  body: number[] | null
}

export type HttpResponse = {
  status: number
  url: string
  headers: { [key in string]: string }
  body: number[]
}

export type ImportedImage = {
  id: string
  name: string
  width: number
  height: number
}

export type Input = {
  apiKey?: string | null
  region?: string | null
  baseUrl?: string | null
}

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

export type Metadata = {
  configured: boolean
  region: string | null
  base_url: string | null
}

export type NewChat = null

export type Number = number

export type OpenHotkeys = null

export type OpenSettings = null

export type PreparedImport = {
  ticket: string
  manifest: JsonValue
  source: string
  styles: string
  convertedManifest: JsonValue
  modules: { [key in string]: string }
}

export type PreparedInstall =
  { format: "current"; path: string; id: string } | { format: "legacy"; prepared: PreparedImport }

export type PublicCustomProvider = PublicCustomProvider_Serialize | PublicCustomProvider_Deserialize

export type PublicCustomProvider_Deserialize = {
  id: string
  name: string
  baseUrl: string
  models: CustomModel_Deserialize[]
}

export type PublicCustomProvider_Serialize = {
  id: string
  name: string
  baseUrl: string
  models: CustomModel_Serialize[]
}

export type RefreshedTokens = {
  access_token: string
  refresh_token: string
}

export type Result<T, E> = ({ Ok: T } & { Err?: never }) | ({ Err: E } & { Ok?: never })

export type RuntimeExit = {
  code: number | null
  signal: number | null
}

export type RuntimeLines = string[]

export type Snapshot = Snapshot_Serialize | Snapshot_Deserialize

export type Snapshot_Deserialize = {
  revision: number
  appliedRevision: number | null
  providers: { [key in string]: Metadata }
  customProviders: PublicCustomProvider_Deserialize[]
  status: string
  error: string | null
}

export type Snapshot_Serialize = {
  revision: number
  appliedRevision: number | null
  providers: { [key in string]: Metadata }
  customProviders: PublicCustomProvider_Serialize[]
  status: string
  error: string | null
}

export type StagedImport = {
  path: string
  id: string
  version: string
  source: string
}

/**
 *  The updater state machine (VSCode abstractUpdateService). `AvailableForDownload` is
 *  stored but never emitted: a hit is downloaded straight away.
 */
export type State =
  | { type: "uninitialized" }
  | { type: "disabled"; reason: DisablementReason }
  | { type: "idle" }
  | { type: "checkingForUpdates" }
  | { type: "availableForDownload"; update: UpdateInfo }
  | { type: "downloading"; update: UpdateInfo; downloadedBytes: number | null; totalBytes: number | null }
  | { type: "ready"; update: UpdateInfo }
  | { type: "restarting"; update: UpdateInfo }

export type TestResult = {
  ok: boolean
  code: string
  message: string
  status: number | null
  latencyMs: number | null
}

export type UpdateInfo = {
  version: string
  filename: string
  signature: string
  contentLength: number | null
}

export type Value = JsonValue

export type ZoomIn = null

export type ZoomOut = null
